name: SnowballFight
main: SnowballFight\Main
version: 0.2.0
api: [3.0.0-ALPHA9,3.0.0-ALPHA8,3.0.0-ALPHA7]
author: chell_uoxou
authors: [chell_uoxou]
description: Snowball Fight PVP System for MCPE
websites: https://github.com/chell-uoxou/SnowballFight
commands:
 sbf:
  usage: sbf < join | cancel | start | end | add | status | edit >